"""empty message

Revision ID: 4abbe43dfac
Revises: None
Create Date: 2015-09-18 16:52:33.536137

"""

# revision identifiers, used by Alembic.
revision = '4abbe43dfac'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dataset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('uploaded_time', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('db_search',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('params', postgresql.JSON(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('celery_id', sa.String(length=36), nullable=True),
    sa.Column('remote_directory', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=25), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('celery_id'),
    sa.UniqueConstraint('remote_directory')
    )
    op.create_table('ms1_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('original_filename', sa.String(length=150), nullable=True),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ms2_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('scans', sa.Integer(), nullable=True),
    sa.Column('original_filename', sa.String(length=150), nullable=True),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('celery_search_task',
    sa.Column('child_task_id', sa.String(length=36), nullable=False),
    sa.Column('group_task_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('last_updated', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['group_task_id'], ['db_search.celery_id'], ),
    sa.PrimaryKeyConstraint('child_task_id')
    )
    op.create_table('dta_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('original_filename', sa.String(length=150), nullable=True),
    sa.Column('dbsearch_id', sa.Integer(), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('flags', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['dbsearch_id'], ['db_search.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sqt_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('original_filename', sa.String(length=150), nullable=True),
    sa.Column('dbsearch_id', sa.Integer(), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('scans', sa.Integer(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['dbsearch_id'], ['db_search.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sqt_file')
    op.drop_table('dta_file')
    op.drop_table('celery_search_task')
    op.drop_table('ms2_file')
    op.drop_table('ms1_file')
    op.drop_table('db_search')
    op.drop_table('dataset')
    ### end Alembic commands ###
