"""empty message

Revision ID: 5aa28e974c
Revises: None
Create Date: 2015-08-22 18:05:46.610818

"""

# revision identifiers, used by Alembic.
revision = '5aa28e974c'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dataset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('uploaded_time', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('db_search',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('params', postgresql.JSON(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ms1_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('original_filename', sa.String(length=150), nullable=True),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ms2_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('scans', sa.Integer(), nullable=True),
    sa.Column('original_filename', sa.String(length=150), nullable=True),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dta_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('original_filename', sa.String(length=150), nullable=True),
    sa.Column('dbsearch_id', sa.Integer(), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('flags', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['dbsearch_id'], ['db_search.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sqt_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('original_filename', sa.String(length=150), nullable=True),
    sa.Column('dbsearch_id', sa.Integer(), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('scans', sa.Integer(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['dbsearch_id'], ['db_search.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sqt_file')
    op.drop_table('dta_file')
    op.drop_table('ms2_file')
    op.drop_table('ms1_file')
    op.drop_table('db_search')
    op.drop_table('dataset')
    ### end Alembic commands ###
